/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SummaryImport } from './routes/summary'
import { Route as ProfileImport } from './routes/profile'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as AuthCallbackImport } from './routes/auth.callback'
import { Route as IndexImport } from './routes/index'
import { Route as SummaryIndexImport } from './routes/summary/index'
import { Route as SummaryDetailsImport } from './routes/summary/details'
import { Route as SummaryAnalyticsImport } from './routes/summary/analytics'
import { Route as ProfileIndexImport } from './routes/profile/index'
import { Route as ProfileSettingsImport } from './routes/profile/settings'
import { Route as ProfileActivityImport } from './routes/profile/activity'

// Create/Update Routes

const SummaryRoute = SummaryImport.update({
  path: '/summary',
  getParentRoute: () => rootRoute,
} as any)

const ProfileRoute = ProfileImport.update({
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const AuthCallbackRoute = AuthCallbackImport.update({
  path: '/auth/callback',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SummaryIndexRoute = SummaryIndexImport.update({
  path: '/',
  getParentRoute: () => SummaryRoute,
} as any)

const SummaryDetailsRoute = SummaryDetailsImport.update({
  path: '/details',
  getParentRoute: () => SummaryRoute,
} as any)

const SummaryAnalyticsRoute = SummaryAnalyticsImport.update({
  path: '/analytics',
  getParentRoute: () => SummaryRoute,
} as any)

const ProfileIndexRoute = ProfileIndexImport.update({
  path: '/',
  getParentRoute: () => ProfileRoute,
} as any)

const ProfileSettingsRoute = ProfileSettingsImport.update({
  path: '/settings',
  getParentRoute: () => ProfileRoute,
} as any)

const ProfileActivityRoute = ProfileActivityImport.update({
  path: '/activity',
  getParentRoute: () => ProfileRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileImport
      parentRoute: typeof rootRoute
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexImport
      parentRoute: typeof ProfileImport
    }
    '/profile/settings': {
      id: '/profile/settings'
      path: '/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof ProfileSettingsImport
      parentRoute: typeof ProfileImport
    }
    '/profile/activity': {
      id: '/profile/activity'
      path: '/activity'
      fullPath: '/profile/activity'
      preLoaderRoute: typeof ProfileActivityImport
      parentRoute: typeof ProfileImport
    }
    '/summary': {
      id: '/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof SummaryImport
      parentRoute: typeof rootRoute
    }
    '/summary/': {
      id: '/summary/'
      path: '/'
      fullPath: '/summary/'
      preLoaderRoute: typeof SummaryIndexImport
      parentRoute: typeof SummaryImport
    }
    '/summary/details': {
      id: '/summary/details'
      path: '/details'
      fullPath: '/summary/details'
      preLoaderRoute: typeof SummaryDetailsImport
      parentRoute: typeof SummaryImport
    }
    '/summary/analytics': {
      id: '/summary/analytics'
      path: '/analytics'
      fullPath: '/summary/analytics'
      preLoaderRoute: typeof SummaryAnalyticsImport
      parentRoute: typeof SummaryImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  AuthCallbackRoute,
  DashboardRoute,
  ProfileRoute: ProfileRoute.addChildren({
    ProfileIndexRoute,
    ProfileSettingsRoute,
    ProfileActivityRoute,
  }),
  SummaryRoute: SummaryRoute.addChildren({
    SummaryIndexRoute,
    SummaryDetailsRoute,
    SummaryAnalyticsRoute,
  }),
})

/* prettier-ignore-end */
